/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testRollMethod() {
        Library library = new Library();
        int[] rolls = library.roll(4);
        assertEquals(4, rolls.length, "Array length should be 4");
    }

    @Test void testDuplicatesMethod() {
        Library library = new Library();
        int[] firstTest = {1, 2, 3, 4, 5};
        assertFalse(library.hasDuplicates(firstTest), "No duplicates");

        int[] secondTest = {1, 1, 2, 4, 5};
        assertTrue(library.hasDuplicates(secondTest), "Duplicates in Array");
    }

    @Test void testCalcAverageMethod() {
        Library library = new Library();
        int[] testArray = {1, 2, 3, 4, 5};

        double expectedAvg = 3;
        double actualAvg = library.calcAverage(testArray);

        assertEquals(expectedAvg, actualAvg, "Average match");
    }


}

