
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package basiclibrary;

import java.util.Random;
public class Library {
    public int[] roll(int nums) {
        int[] rolls = new int[nums];
        Random random = new Random();

        for (int i = 0; i < nums; i++) {

            rolls[i] = random.nextInt(6) + 1;
        }
        return rolls;

    }
}
