/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package linter;

import org.junit.jupiter.api.Test;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import static org.junit.jupiter.api.Assertions.*;

class JavaScriptLinterTest {

    @Test
    void javascriptLinterTest() throws IOException {
        Path filePath = Paths.get("src/main/resources/gates.js");
        String errorMessage = App.checkFile(filePath);
        assertTrue(errorMessage.contains("Missing semicolon"));
    }
}


